cd 6DDF; bash scripts/ddg_analysis_interface.sh 6DDF_top10.lst 6DDF A B
cd ../6OS0; bash scripts/ddg_analysis_interface.sh 6OS0_top10.lst 6OS0 A B
cd ../5VBL; bash scripts/ddg_analysis_interface.sh 5VBL_top10.lst 5VBL A B
cd ../5GLH; bash scripts/ddg_analysis_interface.sh 5GLH_top10.lst 5GLH A B
cd ../6MEO; bash scripts/ddg_analysis_interface.sh 6MEO_top10.lst 6MEO A B
cd ../4RWS; bash scripts/ddg_analysis_interface.sh 4RWS_top10.lst 4RWS A B
cd ../5WB2; bash scripts/ddg_analysis_interface.sh 5WB2_top10.lst 5WB2 A B
cd ../5UIW; bash scripts/ddg_analysis_interface.sh 5UIW_top10.lst 5UIW A B
cd ../6C1Q; bash scripts/ddg_analysis_interface.sh 6C1Q_top10.lst 6C1Q A B
