scripts/relax_no_ligand.slurm 6DDF/6DDF_refined.pdb 6DDF 6DDF 
scripts/relax_no_ligand.slurm 6C1Q/6C1Q_refined.pdb 6C1Q 6C1Q 
scripts/relax_no_ligand.slurm 6OS0/6OS0_refined.pdb 6OS0 6OS0 
scripts/relax_no_ligand.slurm 5VBL/5VBL_refined.pdb 5VBL 5VBL 
scripts/relax_no_ligand.slurm 5GLH/5GLH_refined.pdb 5GLH 5GLH 
scripts/relax_no_ligand.slurm 6MEO/6MEO_refined.pdb 6MEO 6MEO 
scripts/relax_no_ligand.slurm 4RWS/4RWS_refined.pdb 4RWS 4RWS 
scripts/relax_no_ligand.slurm 5WB2/5WB2_refined.pdb 5WB2 5WB2 
scripts/relax_no_ligand.slurm 5UIW/5UIW_refined.pdb 5UIW 5UIW 
scripts/relax_no_ligand.slurm 5UIW/5UIW_refined.pdb 5UIW 5UIW 
